#stages:
#  - build
#  - deploy

build:
  image: docker.ii.org.nz/openstack/build-packages:buildv1
  stage: deploy
  script:
    - git config --global user.email "not@now.com"
    - git config --global user.name "Fixme Later"
    - git commit -m 'throw away removal of .gitlab-ci.yml'
    - gbp buildpackage --git-ignore-branch
    - ls -la
    - pwd 
    - sleep 1000000

  tags:
    - iimac-docker